[package]
name = "wooting-fun"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wooting-rgb = "0.3.0"
wooting-rgb-sys = "0.3.0"
image = "0.24.7"